using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading;

namespace SimpleExample
{
    /// <summary>
    ///     A simple implementation to generate a random fortune cookie
    /// </summary>
    public class RandomFortuneService : IFortuneService
    {
        private readonly Random r = new Random();
        private List<string> fortunes = new List<string>();

        public RandomFortuneService()
        {
            ReadFortunes();
        }

        public FortuneCookie GetACookie()
        {
            return new FortuneCookie
                   {
                       Author = "Confutius",
                       Message = GetAMessage(),
                   };
        }

        public void AddCookie(FortuneCookie cookie)
        {
            this.fortunes.Add(cookie.Message);
            IFortuneCallback callbackChannel = OperationContext.Current.GetCallbackChannel<IFortuneCallback>();
            callbackChannel.OnCookieAdded(cookie);
        }

        private string GetAMessage()
        {
            int next = r.Next(0, fortunes.Count);
            return fortunes[next];
        }

        private void ReadFortunes()
        {
            #region fortunes

            fortunes = new List<string>
                       {
                           "He who throws dirt is losing ground.",
                           "A woman who seeks to be equal with men lacks ambition. Ouch!!!",
                           "The greatest danger could be your stupidity.",
                           "He who laughs last is laughing at you.",
                           "A closed mouth gathers no feet.",
                           "A conclusion is simply the place where you got tired of thinking.",
                           "A cynic is only a frustrated optimist.",
                           "A fanatic is one who can't change his mind, and won't change the subject.",
                           "The world may be your oyster, but it doesn't mean you'll get its pearl.",
                           "Flattery will go far tonight.",
                           "Our first and last love...is self love.",
                           "You were born with the skill to communicate with people easily.",
                           "You are talented in many ways.",
                           "Any rough times are behind you.",
                           "Grand adventures await those who are willing to turn the corner.",
                           "The smart thing is to prepare for the unexpected.",
                           "There is yet time enough for you to take a different path.",
                           "You are very expressive and positive in words, act and feeling.",
                           "A scholars ink lasts longer than a martyrs blood.",
                           "Funny thing about humility. Just when you think you've got it, you've lost it.",
                           "Little and often makes much.",
                           "The days you work are the best days.",
                           "The hard times will begin to fade, joy will take their place.",
                           "The first step to better times is to imagine them.",
                           "When you speak honestly and openly, others truly listen to you.",
                           "It doesn't matter. Who is without a flaw?",
                           "It is much wiser to take advice than to give it.",
                           "A thrilling time is in your immediate future.",
                           "The skills you have gathered will one day come in handy.",
                           "Every excess becomes a vice.",
                           "Keep in close touch with what your competition is doing.",
                           "You can always find happiness at work on Friday.",
                           "The secret of getting ahead is getting started.",
                           "Do not mistake temptation for opportunity.",
                           "You will have gold pieces by the bushel.",
                           "Put the data you have uncovered to beneficial use.",
                           "Your past success will be overshadowed by your future success.",
                           "Skill comes from diligence.",
                           "Don't forget to do good deeds as you accumulate wealth.",
                           "Your money worries are over! Your new job will bring you a huge increase in income.",
                           "Avert misunderstanding by calm, poise and balance.",
                           "Consolidate rather than expand business projects in the near future.",
                           "Delay is the antidote for anger.",
                           "Get ready! Good fortune comes in bunches.",
                           "None of the secrets of success will work unless you do.",
                           "You will be wise not to seek too much from others.",
                           "There is a true and sincere friendship between you and your friends.",
                           "You find beauty in ordinary things, do not lose this ability.",
                           "Your blessing is no more than being safe and sound for the whole lifetime.",
                           "Plan for many pleasures ahead.",
                           "The joyfulness of a man prolongeth his days.",
                           "Something you lost will soon turn up.",
                           "Your heart is pure, and your mind clear, and your soul devout.",
                           "Excitement and intrigue follow you closely wherever you go!",
                           "As the purse is emptied the heart is filled.",
                           "Be mischievous and you will not be lonesome.",
                           "Your flair for the creative takes an important place in your life.",
                           "Your artistic talents win the approval and applause of others.",
                           "Your greatest fortune is the large number of friends you have.",
                           "Don't ask, don't say. Everything lies in silence.",
                           "Be prepared to accept a wondrous opportunity in the days ahead!",
                           "Fame, riches and romance are yours for the asking.",
                           "Good things are being said about you.",
                           "Smiling often can make you look and feel younger.",
                           "Someone is speaking well of you.",
                           "A friend is a present you give yourself.",
                           "A member of your family will soon do something that will make you proud.",
                           "A quiet evening with friends is the best tonic for a long day.",
                           "A single kind word will keep one warm for years.",
                           "Anger begins with folly, and ends with regret.",
                           "Generosity and perfection are your everlasting goals.",
                           "Happy news is on its way to you.",
                           "He who laughs at himself never runs out of things to laugh at.",
                           "Let there be magic in your smile and firmness in your handshake.",
                           "Nature, time and patience are the three best physicians.",
                           "Strong and bitter words indicate a weak cause.",
                           "You will have a very pleasant experience.",
                           "You will step on the soil of many countries.",
                           "Your everlasting patience will be rewarded sooner or later.",
                           "Your great attention to detail is both a blessing and a curse.",
                           "Your ability to juggle many tasks will take you far.",
                           "A friend asks only for your time, not your money.",
                           "You will be invited to an exciting event.",
                           "A warm smile is testimony of a generous nature.",
                           "A secret admirer will soon send you a sign of affection.",
                           "Love asks me no questions, and gives me endless support. --Shakespeare",
                           "In the end there are three things that last: faith, hope and love; and the greatest of these is love.",
                           "Love is for the lucky and the brave.",
                           "If you continually give, you will continually have.",
                           "If you want the rainbow, you must put up with the rain. --Dolly Parton",
                           "If you would be loved, love and be lovable.",
                           "The one you love is closer than you think.",
                           "Love always and deeply.",
                           "Your heart will always make itself known through your words.",
                           "We cannot do great things; only small things with great love. --Mother Teresa",
                           "Love is like wildflowers...it is often found in the most unlikely places.",
                           "Love is the only medicine for a broken heart.",
                           "Love is the triumph of imagination over intelligence. --H.L. Mencken",
                           "Much more grows in the garden than that which is planted there.",
                           "Only love lets us see normal things in an extraordinary way.",
                           "The greatest gift is love.",
                           "There is no limit to love's forbearance, to its trust, its hope, its power to endure.",
                           "Those who have love, have wealth beyond measure.",
                           "To love is to forgive.",
                           "Hearts are not to be had as a gift, hearts are to be earned. --W.B. Yeats",
                           "Your heart is a place to draw true happiness.",
                           "Love conquers all.",
                           "Count your blessings by thinking of those whom you love.",
                           "Warning, do not eat your fortune.",
                           "Demonstrate refinement in everything you do.",
                           "Impossible standards just make life difficult.",
                           "A different world cannot be built by indifferent people.",
                           "Q: What is H2O? A: Caring, 2 parts Hug and 1 part Open-mind.",
                           "Integrity is the essence of everything successful.",
                           "For true love? Send real roses preserved in 24 carat gold!",
                           "Fear is just excitement in need of an attitude adjustment.",
                           "The food here taste so good, even a cave man likes it.",
                           "Perhaps you've been focusing too much on spending.",
                           "Happiness isn't something you remember, it's something you experience.",
                           "Oops...wrong cookie.",
                           "The dream is within you.",
                           "Love is on its way.",
                           "Be direct, usually one can accomplish more that way.",
                           "Use your talents; that's what they are intended for.",
                           "The troubles you have now will pass away quickly.",
                           "See the light at the end of the tunnel.",
                           "Your dream will come true when you least expect it.",
                           "Don't \"face\" reality, let it be the place from which you leap.",
                           "Fortune smiles upon you today.",
                           "Believing is doing.",
                           "Your dynamic eyes have attracted a secret admirer.",
                           "You know where you are going and how to get there.",
                           "Go confidently in the direction of your dreams.",
                           "Your ability to pick a winner will bring you success.",
                           "Humor usually works at the moment of awkwardness.",
                           "Stop procrastinating - starting tomorrow.",
                           "Enthusiastic leadership gets you a promotion when you least expect it.",
                           "You love Chinese food.",
                           "You are far more influential than you think.",
                           "Adjust finances, make budgets, to improve your standing.",
                           "Happiness is not the absence of conflict, but the ability to cope with it.",
                           "An understanding heart warms all that are graced with its presence.",
                           "Your co-workers take pleasure in your great sense of creativity.",
                           "You are one of the people who \"goes places in life.\"",
                           "Others enjoy your company.",
                           "When in doubt, let your instincts guide you.",
                           "A cheerful message is on its way to you.",
                           "A pleasant surprise is in store for you tonight.",
                           "You can't go down the right path without first discovering the path to go down.",
                           "To courageously shoulder the responsibility of one's mistake is character.",
                           "The joyful energy of the day will have a positive affect on you.",
                           "You have a strong desire for a home and your family interests come first.",
                           "Dogs have owners, cats have staff.",
                           "Be patient; in time, even an egg will walk.",
                           "You are not a person who can be ignored.",
                           "You always know the right times to be assertive or to simply wait.",
                           "Reading to the mind is what exercise is to the body.",
                           "Eat something you never tried before.",
                           "Your life becomes more and more of an adventure!",
                           "You need to live authentically, and you can't ignore that.",
                           "Make all you can, save all you can, give all you can.",
                           "A well-aimed spear is worth three.",
                           "To build a better world, start in your community.",
                           "When you can't naturally feel upbeat, it can sometimes help to act as if you did.",
                           "May you have great luck.",
                           "A kind word will keep someone warm for years.",
                           "Nothing in the world is accomplished without passion.",
                           "Human invented language to satisfy the need to complain.",
                           "Accept what comes to you each day.",
                           "A small lucky package is on its way to you soon.",
                           "In human endeavor, chance favors the prepared mind.",
                           "Do not upset the penguin today.",
                           "Don't cry.",
                           "The best way to give credit is to give it away.",
                           "Anything you do, do it well. The last thing you want is to be sorry for what you didn't do.",
                           "Grant yourself a wish this year; only you can do it.",
                           "Love thy neighbor; just don't get caught.",
                           "You will be selected for a promotion because of your accomplishments.",
                           "There are many new opportunities that are being presented to you.",
                           "You will receive a gift from someone that cares about you.",
                           "You are not illiterate.",
                           "Love because it is the only true adventure.",
                           "Treasure what you have.",
                           "The greatest precept is continual awareness.",
                           "A new friend helps you break out of an old routine.",
                           "I have a dream...Time to go to bed.",
                           "Your skill will accomplish what the force of many cannot.",
                           "You will soon be surrounded by good friends and laughter.",
                           "The best is yet to come.",
                           "It is better to be the hammer than the anvil.",
                           "He who climbs a ladder must begin at the first step.",
                           "Action speaks nothing, without the motive.",
                           "Give yourself some peace and quiet for at least a few hours.",
                           "Live each day well and wisely.",
                           "Old dreams never die they just get filed away.",
                           "You can fix it with a little extra energy and a positive attitude.",
                           "Life is a verb.",
                           "A man without aim is like a clock without hands, as useless if it turns as if it stands.",
                           "Many folks are about as happy as they make up their minds to be.",
                           "It's kind of fun to do the impossible.",
                           "Wow! A secret message from your teeth!",
                           "You should be able to make money and hold on to it.",
                           "The human spirit is stronger than anything that can happen to it.",
                           "You have a curious smile and a mysterious nature.",
                           "Your success will astonish everyone.",
                           "It is better to have a hen tomorrow than an egg today.",
                           "Judge each day not by the harvest you reap but by the seeds you plant.",
                           "Your hard work will get payoff today.",
                           "Today is the tomorrow we worried about yesterday.",
                           "There are no shortcuts to any place worth going.",
                           "No matter what your past has been, you have a spotless future.",
                           "Your secret desire to completely change your life will manifest.",
                           "Soon you will be sitting on top of the world.",
                           "You are never selfish with your advice or your help.",
                           "A thrilling time is in store for you.",
                           "It's tough to be fascinating.",
                           "Soon life will become more interesting.",
                           "Luck sometimes visits a fool, but it never sits down with him.",
                           "Aren't you glad you just had a great meal?",
                           "Only talented people get help from others.",
                           "You will be successful in your work.",
                           "You will spend old age in comfort and material wealth.",
                           "When you're about to turn your heart into a stone remember: you do not walk alone.",
                           "You are vigorous in words and action.",
                           "The one who snores will always fall asleep first.",
                           "An alien of some sort will be appearing to you shortly!",
                           "Rest is a good thing, but boredom is its brother.",
                           "Do not be overly judgmental of your loved one's intentions or actions.",
                           "Think of how you can assist on a problem, not whom to blame.",
                           "The life of every woman or man&mdash;the heart of it&mdash;is pure and holy joy.",
                           "Take it easy.",
                           "Trust your intuition. The universe is guiding your life.",
                           "Use your head, but live in your heart.",
                           "Don't find fault, find a remedy.",
                           "It may be those who do most, dream most.",
                           "Your passions sweep you away.",
                           "Listen to yourself more often.",
                           "Think of mother's exhortations more.",
                           "The gambler is like the fisherman; both have beginner's luck.",
                           "You are given the chance to take part in an exciting adventure.",
                           "The simplest answer is to act.",
                           "Keep your feet on the ground even though friends flatter you.",
                           "You are the man of righteousness and integrity.",
                           "He who seeks will find.",
                           "The smart thing to do is to begin trusting your intuitions.",
                           "Your many hidden talents will become obvious to those around you.",
                           "Pick a path with heart.",
                           "It takes more than good memory to have good memories.",
                           "Face facts with dignity.",
                           "Be calm when confronting an emergency crisis.",
                           "Do you believe? Endurance and persistence will be rewarded.",
                           "A new wardrobe brings great joy and change in your life.",
                           "Everyone agrees you are the best.",
                           "Everything will now come your way.",
                           "You will be called to fill a position of high honor and responsibility.",
                           "The eyes believe themselves; the ears believe other people.",
                           "Good beginning is half done.",
                           "It's the worst of times, you need to summon your optimism.",
                           "You are cautious in showing your true self to others.",
                           "Your ability to accomplish tasks will follow with success.",
                           "We all have extraordinary coded within us, waiting to be released.",
                           "Compassion is a way of being.",
                           "You will always have good luck in your personal affairs.",
                           "The pleasure of what we enjoy is lost by wanting more.",
                           "Did you remember to order your takeout also?",
                           "Perhaps you've been focusing too much on that one thing.",
                           "Right now there's an energy pushing you in a new direction.",
                           "Everybody feels lucky for having you as a friend.",
                           "When the moment comes, take the top one.",
                           "Sometimes traveling to new places leads to great transformation.",
                           "There is always a way&mdash;if you are committed.",
                           "Life is too short to waste time hating anyone.",
                           "Don't just spend time, invest it.",
                           "Life always gets harder near the summit.",
                           "Take the chance while you still have the choice.",
                           "It is much easier to be critical than to be correct.",
                           "Enjoy life! It is better to be happy than wise.",
                           "To make the cart go, you must grease the wheels.",
                           "You are contemplating some action which will bring credit upon you.",
                           "Before you wonder \"Am I doing things right?\", ask \"Am I doing the right things?\"",
                           "You may be disappointed if you fail, but you are doomed if you don't try.",
                           "You will always get what you want through your charm and personality.",
                           "The big issues are work, career, or status right now.",
                           "Your emotional currents are flowing powerfully now.",
                           "Any decision you have to make tomorrow is a good decision.",
                           "Consume less. Share more. Enjoy life.",
                           "The secret of staying young is good health and lying about your age.",
                           "Spring has sprung. Life is blooming.",
                           "Go ask your mom.",
                           "The possibility of a career change is near.",
                           "The important thing is to never stop questioning.",
                           "Compassion will cure more than condemnation.",
                           "Excuses are easy to manufacture, and hard to sell.",
                           "Put your mind into planning today. Look into the future.",
                           "Listen to life, and you will hear the voice of life crying, Be!",
                           "Broke is only temporary; poor is a state of mind.",
                           "Here we go. \"Moo Shu Cereal\" for breakfast with duck sauce.",
                           "Teamwork: the fuel that allows common people attain uncommon results.",
                           "You will always be surrounded by true friends.",
                           "Hard words break no bones, fine words butter no parsnips.",
                           "We cannot direct the wind, but we can adjust the sails.",
                           "You are offered the dream of a lifetime. Say yes!",
                           "Working out the kinks today will make for a better tomorrow.",
                           "Questions provide the key to unlocking our unlimited potential.",
                           "You will enjoy razor-sharp spiritual vision today.",
                           "The wise are aware of their treasure, while fools follow their vanity.",
                           "Well-arranged time is the surest sign of a well-arranged mind.",
                           "Never bring unhappy feelings into your home.",
                           "This is really a lovely day. Congratulations!",
                           "A golden egg of opportunity falls into your lap this month.",
                           "You are very grateful for the small pleasures of life.",
                           "Today, you should be a passenger. Stay close to a driver for a day.",
                           "Hate is never conquered by hate. Hate is only conquered by love.",
                           "Service is the rent we pay for the privilege of living on this planet.",
                           "Good clothes open many doors. Go shopping.",
                           "The leader seeks to communicate his vision to his followers.",
                           "Great works are performed not by strength, but by perseverance.",
                           "People who are late are often happier than those who have to wait for them.",
                           "Present your best ideas today to an eager and welcoming audience.",
                           "The time is right to make new friends.",
                           "You may be hungry soon; order a takeout now.",
                           "Do not hesitate to look for help, an extra hand should always be welcomed.",
                           "How can you have a beautiful ending without making beautiful mistakes?",
                           "Humor is an affirmation of dignity.",
                           "What's vice today may be virtue tomorrow.",
                           "You have an unusually magnetic personality.",
                           "You will travel to many places.",
                           "Accept yourself.",
                           "Be a generous friend and a fair enemy.",
                           "Never quit!",
                           "Old friends, old wines, and old gold are best.",
                           "Every friend joys in your success.",
                           "You should be able to undertake and complete anything.",
                           "You are a person of strong sense of duty.",
                           "Dream lofty dreams, and as you dream, so shall you become.",
                           "You have a quiet and unobtrusive nature.",
                           "Great thoughts come from the heart.",
                           "You love peace.",
                           "Judge not according to the appearance.",
                           "One who admires you greatly is hidden before your eyes.",
                           "Traveling more often is important for your health and happiness.",
                           "You will be sharing great news with all people you love",
                           "You have a reputation for being straightforward and honest.",
                           "You are always welcome in any gathering.",
                           "You will be traveling and coming into a fortune.",
                           "Open up your heart; it can always be closed again.",
                           "Being happy is not always being perfect.",
                           "Next time you have the opportunity, go on a roller coaster.",
                           "Try everything once, even the things you don't think you will like.",
                           "Life is too short to hold grudges.",
                           "Dream your dream and your dream will dream of you.",
                           "Being alone and being lonely are two different things.",
                           "Tomorrow, take a moment to do something just for yourself.",
                           "Someone close to you is waiting for you to call.",
                           "A virtual fortune cookie will not satisfy your hunger like that of a home made one.",
                           "Smile. Tomorrow is another day.",
                           "You can never be certain of success, but you can be certain of failure if you never try.",
                           "It takes ten times as many muscles to frown as it does to smile.",
                           "Shoot for the moon! If you miss you will still be amongst the stars.",
                           "Keep your eyes open. You never know what you might see.",
                           "Tell them what you really think. Otherwise, nothing will change.",
                           "Let your heart make your decisions; it does not get as confused as your head.",
                           "Working hard will make you live a happy life."
                       };

            #endregion
        }
    }
}